### ISSUE TITLE
Issue calculating CD/CW/WW/WD with CCAM ERA5

### ISSUE THREAD

**Issue by ngben** [AusClimateService/indices#9]
Not sure what's changed but I can't seem to calculate CD/CW/WW/WD indices in CCAM ERA5. 

I think it's something to do with the lat bounds and CCAM has had some issues previously with lat/lon bounds and floating points, however I had previously calculated these indices using icclim 6.0.0 about 2 weeks ago. I checked the raw input files `/g/data/xv83/mxt599/ccam_era5_evaluation_aus-10i_12km/drs_cordex/CORDEX/output/AUS-10i/CSIRO/ECMWF-ERA5/evaluation/r1i1p1f1/CSIRO-CCAM-2203/v1/day/tas` and `/g/data/xv83/mxt599/ccam_era5_evaluation_aus-10i_12km/drs_cordex/CORDEX/output/AUS-10i/CSIRO/ECMWF-ERA5/evaluation/r1i1p1f1/CSIRO-CCAM-2203/v1/day/pr` and they haven't been changed since the start of November. Other indices calculate ok so far. 

`2022-12-05 09:38:09,633 Array size: (15706, 611, 928)
2022-12-05 09:38:09,633 Chunk size: Frozen({'time': (15706,), 'lat': (37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 19), 'lon': (56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 32)})
2022-12-05 09:38:10,095 Array size: (15706, 611, 928)
2022-12-05 09:38:10,096 Chunk size: Frozen({'time': (15706,), 'lat': (37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 19), 'lon': (56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 32)})
2022-12-05 09:38:10,096    ********************************************************************************************
2022-12-05 09:38:10,096    *                                                                                          *
2022-12-05 09:38:10,096    *          icclim                6.1.3   *
2022-12-05 09:38:10,096    *                                                                                          *
2022-12-05 09:38:10,096    *                                                                                          *
2022-12-05 09:38:10,096    *          Sun Dec  4 22:38:10 2022                                                    *
2022-12-05 09:38:10,096    *                                                                                          *
2022-12-05 09:38:10,096    *          BEGIN EXECUTION                                                                 *
2022-12-05 09:38:10,096    *                                                                                          *
2022-12-05 09:38:10,096    ********************************************************************************************
2022-12-05 09:38:10,096 Processing: 0%
Traceback (most recent call last):
  File "/g/data/xv83/bxn599/ACS/icclim/run_icclim.py", line 526, in <module>
    main(args)
  File "/g/data/xv83/bxn599/ACS/icclim/run_icclim.py", line 369, in main
    index = icclim.index(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/icclim/main.py", line 413, in index
    climate_vars_dict = read_in_files(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/icclim/models/climate_variable.py", line 223, in read_in_files
    return _build_in_file_dict(in_files, var_names, threshold, standard_index)
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/icclim/models/climate_variable.py", line 235, in _build_in_file_dict
    input_dataset = read_dataset(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/icclim/pre_processing/input_parsing.py", line 65, in read_dataset
    return xr.merge(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/xarray/core/merge.py", line 1025, in merge
    merge_result = merge_core(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/xarray/core/merge.py", line 757, in merge_core
    variables, out_indexes = merge_collected(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/xarray/core/merge.py", line 302, in merge_collected
    merged_vars[name] = unique_variable(
  File "/g/data/xv83/dbi599/miniconda3/envs/icclim/lib/python3.10/site-packages/xarray/core/merge.py", line 156, in unique_variable
    raise MergeError(
xarray.core.merge.MergeError: conflicting values for variable 'lat_bnds' on objects to be combined. You can skip this check by specifying compat='override'.`

**Comment by DamienIrving** [comment]
I think the easiest solution is probably just to remove the `lat_bnds` and `lon_bnds` variables when the files are read in. I've done that in https://github.com/AusClimateService/indices/commit/b27d5f97dfb299e99e73898eeab6602fa1845aca - let me know if that solves the problem.

**Comment by ngben** [comment]
Thanks Damien! This seems to be working fine now.
